### ISSUE TITLE
There was a problem in my own reproduction.

### ISSUE THREAD

**Issue by catsay217994** [Ridter/acefile#1]
What is the specific meaning of hdr_crc and reserved1 in the ACE file? There was a problem when I was testing myself.

**Comment by VantIer** [comment]
> What is the specific meaning of hdr_crc and reserved1 in the ACE file? There was a problem when I was testing myself.

Cyclic Redundancy Check. https://research.checkpoint.com/extracting-code-execution-from-winrar/
They explained the role of this and mentioned the need to modify it.
reserved1, it doesn't seem to work, or they didn't mention how to use it.
