### ISSUE TITLE
acefile.py: ambiguous version string, undescribed modifications

### ISSUE THREAD

**Issue by droe** [Ridter/acefile#5]
You are using acefile.py - nice to see it put to good use!

It seems that you made a few minor modifications to acefile.py `0.6.10` included in this repo and did not change the version string. As the original author of acefile.py, I would like to ask you to use a version string that clearly indicates that this is *not* an official version. For example, you could use `0.6.10-Ridter`. I would further suggest that you explain in the `README.md` in this repo what modifications you made to the original acefile.py so people know what to expect.

Thank you!
-Daniel

**Comment by Ridter** [comment]
ok ~

**Comment by droe** [comment]
Much appreciated!
